language: node_js
node_js:
  - 12

services:
  - docker

install: []

before_script:
  - docker pull "beevelop/ionic" || true
  - docker pull "nginx:alpine" || true

script:
  - docker --version
  - docker build -f udagram-feed-api/Dockerfile  -t  mmagnani/udagram-feed-api:latest udagram-feed-api
  - docker build -f udagram-user-api/Dockerfile  -t  mmagnani/udagram-user-api:latest udagram-user-api
  - docker build -f udagram-frontend/Dockerfile  -t  mmagnani/udagram-frontend:latest udagram-frontend

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push mmagnani/udagram-feed-api:latest
  - docker push mmagnani/udagram-user-api:latest
  - docker push mmagnani/udagram-frontend:latest