language: node_js
node_js:
  - 13

services:
  - docker

install:
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
  - chmod +x ./kubectl
  - sudo mv ./kubectl /usr/local/bin/kubectl
  - mkdir ${HOME}/.kube
  - echo "${KUBE_CONFIG}" | base64 --decode > ${HOME}/.kube/config
  
before_script: []

script:
  - cat ${HOME}/.kube/config
  - kubectl get pods