language: node_js
node_js:
  - 12

services:
  - docker

install: []

before_script:
  - docker pull "beevelop/ionic" || true
  - docker pull "nginx:alpine" || true

script:
  - docker --version
  - cd udagram-feed-api && docker build -t udagram-feed-api .
  - docker tag udagram-feed-api mmagnani/udagram-feed-api:latest
  - cd udagram-user-api && docker build -t udagram-user-api .
  - docker tag udagram-user-api mmagnani/udagram-user-api:latest
  - cd udagram-frontend && docker build -t udagram-frontend .
  - docker tag udagram-frontend mmagnani/udagram-frontend:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push mmagnani/udagram-feed-api:latest
  - docker push mmagnani/udagram-user-api:latest
  - docker push mmagnani/udagram-frontend:latest