language: node_js
node_js:
  - 13

services:
  - docker

before_install:
  - openssl aes-256-cbc -K $encrypted_6d312b9e3cc3_key -iv $encrypted_6d312b9e3cc3_iv -in udagram-kubernetes/config.enc -out udagram-kubernetes/config -d

install:
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
  - chmod +x ./kubectl
  - sudo mv ./kubectl /usr/local/bin/kubectl
  - mkdir ${HOME}/.kube
  - mv udagram-kubernetes/config ${HOME}/.kube/
  - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscli-bundle.zip"
  - unzip awscli-bundle.zip
  - sudo ./awscli-bundle/install -i /usr/local/aws -b /bin/aws
  - aws --version
  - mkdir ${HOME}/.aws
  - cat << EOF >>  $HOME/.aws/credentials
    [default]
    aws_access_key_id = ${AWS_KEY}
    aws_secret_access_key = ${AWS_SECRETKEY}
    region = ${AWS_REGION}
    EOF

before_script: []

script:
  - kubectl get pods