language: node_js
node_js:
  - 12

services:
  - docker

install: []

before_script:
  - docker pull "beevelop/ionic" || true
  - docker pull "nginx:alpine" || true

script:
  - docker --version
  - cd udagram-feed-api && docker build -t  mmagnani/udagram-feed-api:latest .
  - cd udagram-user-api && docker build -t  mmagnani/udagram-user-api:latest .
  - cd udagram-frontend && docker build -t  mmagnani/udagram-frontend:latest .

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push mmagnani/udagram-feed-api:latest
  - docker push mmagnani/udagram-user-api:latest
  - docker push mmagnani/udagram-frontend:latest