apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-reverse-proxy-deployment
  namespace: udagram
  labels:
    app: udagram-reverse-proxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-reverse-proxy
  template:
    metadata:
      labels:
        app: udagram-reverse-proxy
    spec:
      containers:
      - name: nginx
        image: mmagnani/udagram-reverse-proxy:latest
        imagePullPolicy: Always          
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"       
        ports:
        - containerPort: 8080
      restartPolicy: Always