apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-user-api-deployment
  namespace: udagram
  labels:
    app: udagram-user-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-user-api
  template:
    metadata:
      labels:
        app: udagram-user-api
    spec:
      containers:
      - name: udagram-user-api
        image: mmagnani/udagram-user-api:latest
        ports:
        - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-feed-api-deployment
  namespace: udagram
  labels:
    app: udagram-feed-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-feed-api
  template:
    metadata:
      labels:
        app: udagram-feed-api
    spec:
      containers:
      - name: nginx
        image: mmagnani/udagram-feed-api:latest
        ports:
        - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-frontend-deployment
  namespace: udagram
  labels:
    app: udagram-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram-frontend
  template:
    metadata:
      labels:
        app: udagram-frontend
    spec:
      containers:
      - name: udagram-frontend
        image: mmagnani/udagram-frontend:latest
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-reverse-proxy-deployment
  namespace: udagram
  labels:
    app: udagram-reverse-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram-reverse-proxy
  template:
    metadata:
      labels:
        app: udagram-reverse-proxy
    spec:
      containers:
      - name: nginx
        image: mmagnani/udagram-reverse-proxy:latest
        ports:
        - containerPort: 80