apiVersion: v1
kind: Service
metadata:
  name: udagram-user-api-service
  namespace: udagram
  labels:
    app: udagram-user-api
spec:
  ports:
  - name: http
    port: 8080
  selector:
    app: udagram-user-api
---
apiVersion: v1
kind: Service
metadata:
  name: udagram-feed-api-service
  namespace: udagram
  labels:
    app: udagram-feed-api
spec:
  ports:
  - name: http
    port: 8080
  selector:
    app: udagram-feed-api
---
apiVersion: v1
kind: Service
metadata:
  name: udagram-frontend-service
  namespace: udagram
  labels:
    app: udagram-frontend
spec:
  ports:
  - name: http
    port: 80
  selector:
    app: udagram-frontend
---
apiVersion: v1
kind: Service
metadata:
  name: udagram-reverse-proxy-service
  namespace: udagram
  labels:
    app: udagram-reverse-proxy
spec:
  ports:
  - name: http
    port: 80
  selector:
    app: udagram-reverse-proxy